export const shortcutGroups: [string, [string, string][]][] = [
  [
    "Actions",
    [
      ["Superlocal Command", "⌘ K"],
      ["Search", "/"],
      ["Undo", "Z"],
    ],
  ],
  [
    "Navigation",
    [
      ["Next / Previous Conversation", "J / K"],
      ["Next / Previous Message", "N / P"],
      ["Open", "Enter"],
      ["Back", "Esc"],
      ["Next Split Inbox", "Tab"],
      ["Previous Split Inbox", "Shift Tab"],
      ["Open Label Menu", "←"],
      ["Page Down", "Space"],
      ["Page Up", "Shift Space"],
      ["Jump to Top", "⌘ ↑"],
      ["Jump to Bottom", "⌘ ↓"],
      ["Switch pinned mailboxes", "Control 1–9"],
      ["Unified inbox", "Control 0"],
      ["Move Focus", "→ ← ↓ ↑"],
    ],
  ],
  [
    "Conversations",
    [
      ["Mark Done", "E"],
      ["Done + record not important to me", "W"],
      ["Mark not Done", "Shift E"],
      ["Remind Me (Snooze)", "H"],
      ["Star", "S"],
      ["Mark Read or Unread", "U"],
      ["Mute", "Shift M"],
      ["Trash", "#"],
      ["Mark as Spam", "!"],
      ["Unsubscribe", "⌘ U"],
      ["Print", "⌘ P"],
      ["Select Conversation", "X"],
      ["Clear Selection", "Esc"],
      ["Select All From Here", "⌘ A"],
      ["Select All", "⌘ Shift A"],
      ["Comment", "M"],
      ["Delete Comment", "⌘ Delete"],
    ],
  ],
  [
    "Labels",
    [
      ["Move", "V"],
      ["Add or Remove Label", "L"],
      ["Remove Label", "Y"],
      ["Remove Label, Next", "["],
      ["Remove Label, Previous", "]"],
      ["Remove All Labels", "Shift Y"],
    ],
  ],
  [
    "Messages",
    [
      ["Compose", "C"],
      ["Reply All", "Enter"],
      ["Reply", "R"],
      ["Forward", "F"],
      ["Open Links & Attachments", "⌘ O"],
      ["Cycle Through Links", "Tab"],
      ["Expand Message", "O"],
      ["Expand/Collapse Header", "Shift H"],
      ["Expand All Messages", "Shift O"],
      ["Show New Messages", "Shift N"],
      ["Use Snippet", "⌘ ;"],
    ],
  ],
  [
    "Compose",
    [
      ["To", "⌘ Shift O"],
      ["Cc", "⌘ Shift C"],
      ["Bcc", "⌘ Shift B"],
      ["From", "⌘ Shift F"],
      ["Edit Subject", "⌘ Shift S"],
      ["Attach", "⌘ Shift U"],
      ["Discard Draft", "⌘ Shift ,"],
      ["Instant Intro (to BCC)", "⌘ Shift I"],
      ["Remind me", "⌘ Shift H"],
      ["Send later", "⌘ Shift L"],
      ["Use Snippet Inline", ";"],
      ["Insert Emoji", ":"],
      ["Send", "⌘ Enter"],
      ["Send Instantly", "⌘ Shift Z"],
      ["Send + Mark Done", "⌘ Shift Enter"],
    ],
  ],
  [
    "Pop Out Compose",
    [
      ["Pop Out Compose", "Shift C"],
      ["Reply All, Pop Out Draft", "Shift Enter"],
      ["Reply, Pop Out Draft", "Shift R"],
      ["Forward, Pop Out Draft", "Shift F"],
      ["Pop Out Draft", "⌘ Shift P"],
      ["Pop In Draft", "⌘ Shift P"],
      ["Pop Out Draft & Search", "⌘ /"],
      ["Toggle Focus", "⌘ D"],
    ],
  ],
  [
    "Format",
    [
      ["Bold", "⌘ B"],
      ["Italics", "⌘ I"],
      ["Underline", "⌘ U"],
      ["Hyperlink", "⌘ K"],
      ["Color", "⌘ O"],
      ["Strikethrough", "⌘ Shift X"],
      ["Numbers", "⌘ Shift 7"],
      ["Bullets", "⌘ Shift 8"],
      ["Quote", "⌘ Shift 9"],
      ["Indent List", "Tab"],
      ["Outdent List", "Shift Tab"],
      ["Increase Indent", "⌘ ]"],
      ["Decrease Indent", "⌘ ["],
    ],
  ],
  [
    "Folders",
    [
      ["Go to Inbox", "G then I"],
      ["Go to Important", "G then I"],
      ["Go to Other", "G then O"],
      ["Go to Starred", "G then S"],
      ["Go to Drafts", "G then D"],
      ["Go to Sent", "G then T"],
      ["Go to Done", "G then E"],
      ["Go to Reminders", "G then H"],
      ["Go to Muted", "G then M"],
      ["Go to Snippets", "G then ;"],
      ["Go to Spam", "G then !"],
      ["Go to Trash", "G then #"],
      ["Go to All Mail", "G then A"],
      ["Go to Label …", "G then L"],
    ],
  ],
  [
    "Windows",
    [
      ["New Tab", "⌘ T"],
      ["Next Tab", "⌘ Shift ]"],
      ["Previous Tab", "⌘ Shift ["],
      ["Close Tab", "⌘ W"],
      ["Increase Font Size", "⌘ ="],
      ["Decrease Font Size", "⌘ -"],
      ["Reset Font Size", "⌘ 0"],
      ["Find Within Page", "⌘ F"],
      ["Copy Private Link", "Control /"],
    ],
  ],
  [
    "Calendar",
    [
      ["Open Day", "0"],
      ["Open Week", "2"],
      ["Previous Day/Week", "–"],
      ["Next Day/Week", "="],
      ["Share Availability", "⌘ Shift A"],
      ["Create Event", "B"],
      ["Create Empty Event", "Shift B"],
    ],
  ],
  [
    "Filters",
    [
      ["Unread", "Shift U"],
      ["Starred", "Shift S"],
      ["Important", "Shift I"],
      ["No reply", "Shift R"],
    ],
  ],
];
